[pytest]
markers =
	smoke: marker for smoke tests
	regression: marker for regression tests


# pytest -s -v -m smoke test_1.py
# pytest -s -v -m "mark_name_1 and or not mark_name_2" test_1.py

# .skip flag doesn't require add declaration in pytest.ini
# .skip flag should be the last in flags of methods